// Auto-generated by `supabase gen types typescript`
// Stub — regenerate after Supabase schema is deployed.
// Run: npx supabase gen types typescript --linked > src/types/database.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          name: string | null
          email: string | null
          role: "USER" | "ADMIN"
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          name?: string | null
          email?: string | null
          role?: "USER" | "ADMIN"
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string | null
          email?: string | null
          role?: "USER" | "ADMIN"
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [{ foreignKeyName: "profiles_id_fkey"; columns: ["id"]; referencedRelation: "users"; referencedColumns: ["id"] }]
      }
      items: {
        Row: {
          id: string
          title: string
          description: string | null
          type: "BOOK" | "MUSIC" | "MOVIE" | "GAME" | "TOY" | "OTHER"
          status: "AVAILABLE" | "BORROWED" | "RESERVED" | "UNAVAILABLE" | "GIVEN_AWAY" | "LOST"
          cover_image: string | null
          isbn: string | null
          author: string | null
          publisher: string | null
          published_at: string | null
          metadata: Json
          collection_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          type?: "BOOK" | "MUSIC" | "MOVIE" | "GAME" | "TOY" | "OTHER"
          status?: "AVAILABLE" | "BORROWED" | "RESERVED" | "UNAVAILABLE" | "GIVEN_AWAY" | "LOST"
          cover_image?: string | null
          isbn?: string | null
          author?: string | null
          publisher?: string | null
          published_at?: string | null
          metadata?: Json
          collection_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string | null
          type?: "BOOK" | "MUSIC" | "MOVIE" | "GAME" | "TOY" | "OTHER"
          status?: "AVAILABLE" | "BORROWED" | "RESERVED" | "UNAVAILABLE" | "GIVEN_AWAY" | "LOST"
          cover_image?: string | null
          isbn?: string | null
          author?: string | null
          publisher?: string | null
          published_at?: string | null
          metadata?: Json
          collection_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          { foreignKeyName: "items_collection_id_fkey"; columns: ["collection_id"]; referencedRelation: "collections"; referencedColumns: ["id"] }
        ]
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      role: "USER" | "ADMIN"
      item_type: "BOOK" | "MUSIC" | "MOVIE" | "GAME" | "TOY" | "OTHER"
      item_status: "AVAILABLE" | "BORROWED" | "RESERVED" | "UNAVAILABLE" | "GIVEN_AWAY" | "LOST"
      loan_status: "PENDING" | "APPROVED" | "REJECTED" | "RETURNED" | "OVERDUE" | "LOST"
      request_type: "BORROWED_ITEM" | "SUGGESTION"
      request_status: "PENDING" | "PROCESSING" | "COMPLETED" | "REJECTED"
      setting_type: "STRING" | "BOOLEAN" | "NUMBER" | "JSON"
    }
  }
}

export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"]
export type Enums<T extends keyof Database["public"]["Enums"]> = Database["public"]["Enums"][T]
